### ISSUE TITLE
Error on game start due to science pack productivity tech (1.0.6)

### ISSUE THREAD

**Issue by daniele-bondi** [ZacharyDK/Secretas#4]
I get the following error on startup.

```
12.272 Error ModManager.cpp:1752: Technology science-pack-productivity: there is no lab that will accept all of the science packs this technology requires.
Science packs: maraxsis-salted-science, automation-science-pack, logistic-science-pack, military-science-pack, chemical-science-pack, production-science-pack, utility-science-pack, space-science-pack, metallurgic-science-pack, agricultural-science-pack, electromagnetic-science-pack, janus-time-science-pack, cerys-science-pack, hydraulic-science-pack, cryogenic-science-pack, golden-science-pack, particle-physics-pack, bioluminescent-science-pack, electrochemical-science-pack, promethium-science-pack, slp-sun-science-pack
```

I believe this happens because the cerys science pack is not used in normal labs, but only in dedicated structures on cerys which accepts only red, green, yellow and cerys science.

I guess this could be fixed by adding a special exception for cerys, I don't have a better idea.

**Comment by hohounk** [comment]
I know of at least one other mod that added science packs to researches and had the same issue. They too just excluded cerys as that made the most sense "lore"-wise from cerys-side.

**Comment by Frontrider** [comment]
Yeah, something like that was on the table for this planetslib feature. I *clould* just take all science packs from the normal lab and set the promethium science's tech (and every marked techs after it) to that list.

https://github.com/danielmartin0/PlanetsLib/pull/29

**Comment by Fr-Dae** [comment]
same here
```  14.300 Error ModManager.cpp:1751: Technology science-pack-productivity: there is no lab that will accept all of the science packs this technology requires.
Science packs: maraxsis-salted-science, automation-science-pack, logistic-science-pack, military-science-pack, chemical-science-pack, production-science-pack, utility-science-pack, space-science-pack, metallurgic-science-pack, agricultural-science-pack, electromagnetic-science-pack, cerys-science-pack, hydraulic-science-pack, cryogenic-science-pack, golden-science-pack, bioluminescent-science-pack, electrochemical-science-pack, promethium-science-pack
  14.716 Info PlayerData.cpp:66: Local player-data.json available, timestamp 1738159541
  14.716 Info PlayerData.cpp:73: Cloud player-data.json unavailable
  14.756 Post-data load graphics options: [Light occlusion: YES]
  15.105 Crop bitmaps.
  15.105 Parallel sprite loader initialized (threads: 4, bitmaps: 2)
  15.218 Initial atlas bitmap size is 8192
  15.224 Created an atlas bitmap (size 4096x1024) [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
  15.224 Loading 3D bitmaps.
  15.250 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
  15.251 Parallel sprite loader initialized (threads: 3, bitmaps: 164)
  15.423 Sprites loaded
  15.433 Generated mipmaps (5) for atlas [0] of size 4096x1024   
  15.434 Custom mipmaps uploaded (116)
  15.469 Video memory usage: 21.31 MB (Atlases: 21.31 MB, Textures: 0.00 MB)
  15.496 Error ControlSettings.cpp:1013: maraxsis-trench-submerge (custom-input): unknown controller_key_sequence: controller-righttrigger + controller-lefttrigger + controller-y
  15.501 Custom inputs active: 102
  15.502 Factorio initialised

```

- Lubuntu 24.10
- Factorio 2.0.32

**Comment by Fr-Dae** [comment]
@ZacharyDK

**Comment by undo-undone** [comment]
```
Failed to load mods: Technology science-pack-productivity: there is no lab that will accept all of the science packs this technology requires.
Science packs: maraxsis-salted-science, automation-science-pack, logistic-science-pack, nanite-science-pack, anomaly-science-pack, quantum-science-pack, ring-science-pack, military-science-pack, chemical-science-pack, production-science-pack, utility-science-pack, space-science-pack, metallurgic-science-pack, agricultural-science-pack, battlefield-science-pack, electromagnetic-science-pack, cerys-science-pack, hydraulic-science-pack, interstellar-science-pack, cryogenic-science-pack, golden-science-pack, bioluminescent-science-pack, electrochemical-science-pack, promethium-science-pack
```
Same issue, I have a planet heavy mod loadout.

**Comment by Frontrider** [comment]
Planets lib will get a function for this, as it is a real compatibility issue between different planet mods. @SimonBrodtmann I'll open an issue on lignumis too when we get to the first PR.

**Comment by ZacharyDK** [comment]
Ugg I hate these errors. Not sure what to do about right now

**Comment by Frontrider** [comment]
This is specifically the next thing we'll be tackling with PlanetsLib @ZacharyDK. We'll give you a wholesale solution, as we do see that it happens with basically almost all mods adding science. 👍

**Comment by ZacharyDK** [comment]
1.0.7 has a mod setting to disable auto population of science-pack-productivity on my end. This should fix the compatibility and work with whatever you do. I'll make a setting in my other mod to handle lab stuff.

**Comment by Fr-Dae** [comment]
reopen please
1.0.7 still the same error,  please turn ON this settings by default, we can't acces to it if the game crash at loading
@ZacharyDK
